set_property PACKAGE_PIN G2 [get_ports {dig_left[3]}]
set_property PACKAGE_PIN C2 [get_ports {dig_left[2]}]
set_property PACKAGE_PIN C1 [get_ports {dig_left[1]}]
set_property PACKAGE_PIN H1 [get_ports {dig_left[0]}]
set_property PACKAGE_PIN G1 [get_ports {dig_right[3]}]
set_property PACKAGE_PIN F1 [get_ports {dig_right[2]}]
set_property PACKAGE_PIN E1 [get_ports {dig_right[1]}]
set_property PACKAGE_PIN G6 [get_ports {dig_right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_left[0]}]
set_property PACKAGE_PIN B4 [get_ports {seg_left[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_left[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_left[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_left[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_left[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_left[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_left[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_left[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg_right[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_right[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_right[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_right[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_right[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_right[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_right[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_left[0]}]
set_property PACKAGE_PIN P17 [get_ports clk_50M]
set_property PACKAGE_PIN P15 [get_ports rst]
#set_property PACKAGE_PIN V1 [get_ports FLAG]
#set_property PACKAGE_PIN R15 [get_ports STA_STO]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50M]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
#set_property IOSTANDARD LVCMOS33 [get_ports FLAG]
#set_property IOSTANDARD LVCMOS33 [get_ports STA_STO]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#set_property PACKAGE_PIN N4 [get_ports en]
#set_property IOSTANDARD LVCMOS33 [get_ports en]


set_property PACKAGE_PIN U4 [get_ports key_1]
set_property PACKAGE_PIN V1 [get_ports key_2]
set_property PACKAGE_PIN R15 [get_ports key_3]
set_property PACKAGE_PIN R11 [get_ports key_4]
set_property IOSTANDARD LVCMOS33 [get_ports key_1]
set_property IOSTANDARD LVCMOS33 [get_ports key_2]
set_property IOSTANDARD LVCMOS33 [get_ports key_3]
set_property IOSTANDARD LVCMOS33 [get_ports key_4]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_50M]

